services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "./secrets:/etc/kafka/secrets"
      - "./data:/var/lib/kafka/data"
    command: "sh -c 'set -x; /etc/kafka/docker/configure && /etc/kafka/docker/run'"
    user: root # root 권한으로 변경
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: "550e8400-e29b-41d4-a716-446655440000"
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092, CONTROLLER://kafka:9093, SSL://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, SSL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, CONTROLLER:PLAINTEXT, SSL:SSL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_NODE_ID: 1
      KAFKA_SSL_KEYSTORE_FILENAME: keystore.p12
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.p12
      KAFKA_SSL_KEYSTORE_PASSWORD: qwer1234

      KAFKA_SSL_TRUSTSTORE_FILENAME: truststore.p12
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.p12
      KAFKA_SSL_TRUSTSTORE_PASSWORD: qwer1234

      KAFKA_SSL_CLIENT_AUTH: "required"

      KAFKA_SSL_KEY_CREDENTIALS: kafka_sslkey_creds.txt
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka_keystore_creds.txt
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka_truststore_creds.txt