spring:
  application:
    name: kafka

  kafka:
    server: localhost:8081
    consumer:
      group-id: single
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all
    topic:
      name: test-topic
      partitinos: 3
      replication-factor: 1