spring:
  application:
    name: kafka

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all
    topic:
      name: test-topic
      partitions: 3
      replication-factor: 1