spring:
  application:
    name: kafka

  kafka:
    bootstrap-servers: localhost:9094
    security:
      protocol: SSL
    properties:
      ssl.truststore.location: file:C:/Users/qkrckstjq/Desktop/backend/kafka/secrets/kafka-client.truststore.jks
      ssl.truststore.password: 1q2w3e4r
      ssl.keystore.location: file:C:/Users/qkrckstjq/Desktop/backend/kafka/secrets/kafka-client.keystore.jks
      ssl.keystore.password: qwer1234
      ssl.key.password: qwer1234
    consumer:
      group-id: test
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all
    topic:
      name: test-topic
      partitions: 3
      replication-factor: 1